# Generated by Django 4.1.4 on 2022-12-30 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='hire_date',
        ),
    ]
