# Generated by Django 4.1.4 on 2022-12-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empinfo', '0002_remove_employee_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
